apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  namespace: nukoolmu
  labels:
    app: myapi
spec:
  selector:
    matchLabels:
      app: myapi
      developer: nukoolmu
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapi
        developer: nukoolmu
    spec:
      containers:
        - name: myapp
          image: nukoolm/myexample:app-c
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"