apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ing
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "nukoolmu.publab.com"
    http:
      paths:
      - pathType: Prefix
        path: "/be-1"
        backend:
          service:
            name: my-service
            port:
              number: 80
