apiVersion: v1
kind: Pod
metadata: 
  name: sample-app
  labels:
    app: sample-app
spec:
  containers:
    - name: sample-app
      image: bash
      envFrom:  
      - configMapRef:  
          name: sample-cm
      command: [ "sleep" ]
      args: [ "infinity" ]
